os: linux
language: rust
rust: stable
cache: cargo

jobs:
  include:
    - stage: test
      addons:
        apt:
          packages:
            - libsdl2-dev
      before_script:
        - rustup toolchain install nightly --allow-downgrade --component rustfmt clippy
        - rustup default nightly
      script:
        - cargo build  --workspace --verbose --all-targets
        - cargo test   --workspace --verbose
        - cargo fmt    --all       --verbose -- --check
        - cargo clippy --workspace --verbose
