[package]
name = "cardboard_math"
version = "0.1.0"
publish = false
edition = "2018"

[dependencies]
cfg-if = "1.0.0"
oorandom = "11.1.2"
getrandom = { version = "0.2.0", features = ["std"] }
serde = { version = "1.0.116", features = ["derive"], optional = true }

[features]
const_fn = []
