name: CI

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          override: true
      - name: Install SDL2
        run: sudo apt-get install libsdl2-dev

      # TODO: cache target/

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --verbose --workspace --all-targets

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --workspace

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --verbose --all -- --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose --workspace
